// Auto-generated by update-gallery.ps1 - do not edit by hand.
// Run it again after adding/removing images in tgminiapprbx/avatars|fons|podfons.
const GALLERY = {
  avatars: ['tgminiapprbx/avatars/amber_glow.jpg', 'tgminiapprbx/avatars/teal_night.jpg', 'tgminiapprbx/avatars/violet_dream.jpg'],
  fons: ['tgminiapprbx/fons/fe76b188ca8feca9e2fe6036d073212c.jpg', 'tgminiapprbx/fons/flaze.jpg'],
  podfons: ['tgminiapprbx/podfons/deep_forest.jpg', 'tgminiapprbx/podfons/midnight_blue.jpg', 'tgminiapprbx/podfons/night_violet.jpg'],
};
