$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$base = 'tgminiapprbx'

$out = @(
  '// Auto-generated by update-gallery.ps1 - do not edit by hand.',
  "// Run it again after adding/removing images in $base/avatars|fons|podfons.",
  'const GALLERY = {'
)

foreach ($key in 'avatars', 'fons', 'podfons') {
  $sub = Join-Path $root (Join-Path $base $key)
  $files = @(Get-ChildItem -Path (Join-Path $sub '*') -File -ErrorAction SilentlyContinue |
    Where-Object { $_.Extension -match '^\.(jpe?g|png)$' } |
    Sort-Object Name)

  $items = foreach ($f in $files) {
    $rel = ($f.FullName.Substring($root.Length + 1) -replace '\\', '/')
    "'$($rel.Replace("'", "''"))'"
  }
  $out += "  $key`: [$($items -join ', ')],"
}

$out += '};'
$out | Set-Content -Path (Join-Path $root 'manifest.js') -Encoding UTF8
Write-Host "manifest.js updated. Run update-gallery.bat again after adding/removing images."